# Generated by Django 2.0.5 on 2018-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=120)),
                ('death', models.CharField(max_length=120)),
            ],
        ),
        migrations.RenameField(
            model_name='tree',
            old_name='location',
            new_name='mainlocation',
        ),
    ]
